apiVersion: v1
kind: Service
metadata:
  labels:
    app: manageemployees-dplmnt
  name: manageemployees-svc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31903
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: manageemployees-dplmnt
  sessionAffinity: None
  type: NodePort
